### ISSUE TITLE
About the implementations of the ADE and FDE

### ISSUE THREAD

**Issue by Blessinglrq** [StanfordASL/Trajectron#10]
Hi, author. Thank you very much for your work. I would like to ask you about the quantitative ADE and FDE results. You said in your paper that you used your own implementations of the ADE and FDE metrics and made a comparison in Table 1, but I don't seem to see any script that can be used to evaluate the results in Table 1. Could you share the script that you evaluated in table 1? thank you

**Comment by BorisIvanovic** [comment]
Hello!

If you're wondering about the specific ADE/FDE implementations, you can see them here: https://github.com/StanfordASL/Trajectron/blob/master/code/utils/eval_utils.py#L23

If you're wondering about the specific file that generated the values in Table 1, thanks for catching that it wasn't uploaded!! My apologies, I've now uploaded it to the repository here: https://github.com/StanfordASL/Trajectron/blob/master/sgan-dataset/Best%20of%20N%20Analyses.ipynb

**Comment by Blessinglrq** [comment]
> Hello!
> 
> If you're wondering about the specific ADE/FDE implementations, you can see them here: https://github.com/StanfordASL/Trajectron/blob/master/code/utils/eval_utils.py#L23
> 
> If you're wondering about the specific file that generated the values in Table 1, thanks for catching that it wasn't uploaded!! My apologies, I've now uploaded it to the repository here: https://github.com/StanfordASL/Trajectron/blob/master/sgan-dataset/Best%20of%20N%20Analyses.ipynb

oh...thanks for your uploaded!!!
