### ISSUE TITLE
Preprocess Datasets for Trajectron

### ISSUE THREAD

**Issue by saranshvora** [StanfordASL/Trajectron#4]
hi @BorisIvanovic how do you preprocess the datasets? I from the mean you take the x, y, vx, vy and ax, ay (please correct me if I am wrong) but what is standard deviation(does it record the history of the pedestrian and then calculates the std deviation)? 

If possible can you share the data preprocessing code as well please?

**Comment by BorisIvanovic** [comment]
Thanks @saranshvora for the reminder! I forgot to upload it in the recent update to the codebase, and have fixed this now. You can find it here: https://github.com/StanfordASL/Trajectron/blob/master/sgan-dataset/format_data.py

**Comment by saranshvora** [comment]
Hi, @BorisIvanovic  great thank you :) no problem :)
