### ISSUE TITLE
Type of edges and categories

### ISSUE THREAD

**Issue by saruvora** [StanfordASL/Trajectron#5]
Hi, @BorisIvanovic I read the paper and I have a few doubts regarding it. Can you explain what are the types of edges T1, T2 and T3? I went through STG in structured RNN paper as well but was not able to figure out properly if you have similar kind of edges like spatial edge and temporal edge. 

For categories, you consider Humans as the only categories, right? and no other object-human interactions?

**Comment by BorisIvanovic** [comment]
We have both spatial and temporal edges, it's just that now those edges have types themselves. For example, when modeling a Pedestrian the Trajectron will have a Ped-Ped temporal edge between different timesteps. If another pedestrian passed alongside them then there would be a Ped-Ped spatial edge created between the two agents. Note that a Ped-Ped temporal edge is different from a Ped-Ped spatial edge (one is temporal, one is spatial).

Correct! Here we're only considering Humans (specifically the type for them is Pedestrians).

**Comment by BorisIvanovic** [comment]
T1, T2, T3 are agent types, so Pedestrian is an example. If the dataset you're interested in working with has Bicycles or Cars, then those could also be distinct types (and indeed they should be given their very different dynamics).

**Comment by saranshvora** [comment]
Hi, @BorisIvanovic  no problem thank you for your reply it was really helpful.
