### ISSUE TITLE
lost files

### ISSUE THREAD

**Issue by Yamguocheng** [StanfordASL/Trajectron#8]
when i run train.py , it lost debug_eval_data.pkl and debug_train_data.pkl . i can't get the files.

**Comment by saruvora** [comment]
You have to generate these files using this [data preprocessor](https://github.com/StanfordASL/Trajectron/blob/master/sgan-dataset/format_data.py) and this will generate .pkl files for you, training and validation sets. Then give those filenames instead of the above mentioned ones.

**Comment by BorisIvanovic** [comment]
The above answer is correct, however you also don't need to generate your own data files if you don't want to. The ETH and UCY pedestrian dataset .pkl files are included with the code under the `sgan-dataset/data` folder.
